// export const HOST:string = 'http://254a2y1767.qicp.vip';// 外网映射地址，一般只有晚上才开机，开机之后才能使用，如需调试请联系
export const HOST: string = 'http://192.168.0.103:5001'; // 内网地址
export const USER_DATA: string = 'USER_DATA';//用户信息
export const DEVICE_INFO: string = 'DEVICE_INFO';// 设备信息
export const MUSIC_PLAYER: string = 'MUSIC_PLAYER';// 音乐播放器
export const MUSIC_MODEL: string = 'MUSIC_MODEL';// 音乐实例对象
export const MUSIC_STORAGE: string = 'MUSIC_STORAGE';// 音乐仓库
export const MUSIC_SEARCH: string = 'MUSIC_SEARCH';// 音乐搜查
export const FAVORITE_MUSIC: string = 'FAVORITE_MUSIC';// 收藏音乐
export const PAGE_SIZE:number = 20;// 收藏音乐
export const MAX_PAGE_SIZE:number = 500;// 每页最大数量